version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"  # app available at http://localhost:8080
    volumes:
      - ./:/var/www/html  # hot reload for local dev
    environment:
      DB_HOST: aws-1-us-east-2.pooler.supabase.com
      DB_PORT: 6543
      DB_USER: postgres.lrbjhcejtnalhjuprtxp
      DB_PASS: TaskManager911
      DB_NAME: postgres


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: linc
      MYSQL_DATABASE: task_management_db
    ports:
      - "3306:3306"  # Expose MySQL port locally (optional)
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: